### ISSUE TITLE
proposal: `.text-match:{substring.with.dots}`

### ISSUE THREAD

**Issue by dgryski** [kanatohodets/carbonsearch#1]
This adds known meta-characters that are already valid in find queries to allow substring matching for text including dots.

The query parsing is not longer a single split command but is still easy to handle.

**Comment by nnuss** [comment]
I like this proposal. I was already reserving braces for future `OR` support so I'd like us to keep that in mind.

**Comment by dgryski** [comment]
@nnuss `{}`'s nest ;)

**Comment by nnuss** [comment]
Of course. `.this-tag:{has.dots}.fruit-flavor:{sweet,savory}.{one-of:these,some-of:those}.{funny-sort:not_very,glob-escaping:{sadface-\}:},nested-glob:{wait_{really,what,dear_god_{no,why}}}}`

**Comment by kanatohodets** [comment]
Monstrosity!

Sounds like a nice thing, although I'd like to find an approach that doesn't conflate 'quote this thing' with OR matching. In any case I think it can wait until after we have more user feedback.

**Comment by JaderDias** [comment]
I really need this feature for text-match:df.root.byte_free, otherwise it will match byte_free from other partitions

**Comment by JaderDias** [comment]
I tried to use * (wildcard) to replace the dot, that doesn't work either

**Comment by kanatohodets** [comment]
@JaderDias: yep, right now carbonsearch doesn't support any special syntax at all, just plain 'service-key:value.service-key:value' queries. 

Some futzing with carbonapi indicates that we might be able to use `[]` for quotes without patching its parser. This would look like: `text-match:[df.root.byte_free]`. This could be a bit confusing for people expecting regex syntax, but might not be so bad. 

If we're open to messing a bit with carbonapi, graphite(tm) doesn't seem to poke around in the middle of metrics, so another option would be to patch graphite-api's parser to not bother with search queries: this would give us a fair degree of flexibility for syntax for quoting, including plain old single or double quotes.

**Comment by kanatohodets** [comment]
This is implemented in https://github.com/kanatohodets/carbonsearch/commit/6d61f5290b52105137b4f8224c8883d8cbdc909d using `<` and `>` for quoting characters. I have no strong feelings about `<` and `>` in particular, other than that `grammar.py` from graphite ignores them, they're not already used in graphite elsewhere (I think?) and they're different for start and end. 

We still need to patch carbonapi to allow `<` and `>`, but that should be fairly straightforward. I'll leave this open until the PR in carbonapi is complete.

**Comment by kanatohodets** [comment]
https://github.com/dgryski/carbonapi/commit/79f91477a4e0c985c4af18bf98c8ed3bfb465cec allows carbonapi to parse `<` and `>` on render requests without erroring.
